# Generated by Django 5.2.4 on 2025-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlotResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point1X",
                    models.FloatField(
                        help_text="X component of the first point/vector."
                    ),
                ),
                (
                    "point1Y",
                    models.FloatField(
                        help_text="Y component of the first point/vector."
                    ),
                ),
                (
                    "point1Z",
                    models.FloatField(
                        help_text="Z component of the first point/vector."
                    ),
                ),
                (
                    "point2X",
                    models.FloatField(
                        help_text="X component of the second point/vector."
                    ),
                ),
                (
                    "point2Y",
                    models.FloatField(
                        help_text="Y component of the second point/vector."
                    ),
                ),
                (
                    "point2Z",
                    models.FloatField(
                        help_text="Z component of the second point/vector."
                    ),
                ),
                (
                    "point3X",
                    models.FloatField(
                        help_text="X component of the third point/vector."
                    ),
                ),
                (
                    "point3Y",
                    models.FloatField(
                        help_text="Y component of the third point/vector."
                    ),
                ),
                (
                    "point3Z",
                    models.FloatField(
                        help_text="Z component of the third point/vector."
                    ),
                ),
                (
                    "relativeError",
                    models.FloatField(help_text="Relative error in this iteration."),
                ),
            ],
            options={
                "verbose_name": "Plot Result",
                "verbose_name_plural": "Plot Results",
                "ordering": ["-id"],
            },
        ),
    ]
